# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('documents', models.TextField(default='')),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TethysServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField(default=9779)),
                ('url', models.URLField(default='localhost')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tethys.TethysServer'),
        ),
    ]
