# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='documents',
            field=models.TextField(blank=True),
        ),
    ]
